config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create, :update, :edit] do
    member do
      get :followings
      get :followers
      get :likes
    end
  end

  resources :posts, only: [:index, :create, :destroy, :edit, :update, :show]
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user, optional: true
  
  has_many :favorites, dependent: :destroy
  has_many :users, through: :favorites
  
  validates :content, presence: true, length: { maximum: 255 }
  validates :genre, presence: true
  def self.search(search)   
        if search  
          where(['content LIKE ?', "%#{search}%"])   
        else  
          all  
        end  
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:show, :edit, :update, :destroy]
  
  def index
    if logged_in?
      @post = current_user.posts.build
    end
  end
  
  def show
  end
  
  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = 'メモを投稿しました'
      redirect_to root_url
    else
      @posts = current_user.feed_posts.order(id: :desc).page(params[:page]).per(30)
      flash.now[:danger] = 'メモの投稿に失敗しました'
      render 'posts/index'
    end
  end
  
  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      flash[:success] = 'メモは正常に更新されました'
      redirect_to @post
    else
      flash.now[:danger] = 'メモは更新されませんでした'
      render :edit
    end
  end
  
  def destroy
    @post.destroy
    flash[:success] = 'メモを削除しました'
    redirect_back(fallback_location: root_path)
  end

  private

  def post_params
    params.require(:post).permit(:content, :genre, :image)
  end

  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    unless @post
      redirect_to root_url
    end
  end
end

app/views/posts/_delete_button.html.erb
<div>
  <% if current_user == post.user %>
    <%= link_to "削除", post, method: :delete, data: { confirm: "本当に削除してもよろしいですか？" }, class: 'btn btn-danger btn-sm' %>
  <% end %>
</div>

app/views/posts/_edit_button.html.erb
<div>
  <% if current_user == post.user %>
    <%= link_to '編集', edit_post_path(post), class: 'btn btn-success btn-sm' %>
  <% end %>
</div>

app/views/posts/_form.html.erb
<% if current_user == post.user %>
  
  <%= form_with(model: post, local: true) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
    
    <div class="edit_genre" >
    <%= f.label :genre, 'ジャンル' %>
    <%= f.select :genre, ['食事', '運動', '美容'] %>
    </div>
    <div class="form-group">
      <p class="gazou">
        <%= f.label :image, '画像をアップロード' %>
        <br>
        <% if f.object.image.present? %>
          <%= image_tag post.image.url, alt: "KIREI_image" %>
        <% end %>
        <%= f.file_field :image %>
      </p>
      <div class="edit_memo" ><%= f.label :content, 'メモ' %></div>
      <%= f.text_area :content, class: 'form-control', rows: 5 %>
    </div>
    <%= f.submit '投稿する', class: 'btn btn-primary btn-block' %>
  <% end %>
     
<% end %>

app/views/posts/_posts.html.erb
<ul class="list-unstyled">
  <% posts.each do |post| %>
    <li class="media mb-3">
      <img class="mr-2 rounded" src="<%= gravatar_url(post.user, { size: 50 }) %>" alt="">
      <div class="media-body">
        <div class="namae">
          <%= link_to post.user.name, user_path(post.user) %> <span class="text-muted">posted at <%= l post.created_at %></span>
        </div>
        <div>
          <p class="text-break mb-0"><mark><%= post.genre %></mark></p>
          <% if post.image? %>
            <%= image_tag post.image.url, alt: "KIREI_image" %>
          <% end %>
        </div>
        <div class="text-break mb-0"><%= simple_format( post.content ) %></div>
        <div class="btn-toolbar">
          <%= render 'posts/edit_button', post: post %>
          <%= render 'favorites/like_button', post: post %>
          <%= render 'posts/delete_button', post: post %>
        </div>
      </div>
    </li>
  <% end %>
</ul>
<%= paginate posts %>

app/views/posts/edit.html.erb
<div class="row">
  <div class="toukou">
    <div class="col-sm-8">
      <h1 class="edit_top" >メモの編集</h1>

      <div class="edit_change" >
        <%= link_to 'Myタイムライン へ', root_path %>
        <br>
        <%= link_to 'Myプロフィール へ', user_path(@current_user) %>
      </div>
      <br>
      <%= render 'form', post: @post %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<% if logged_in? %>
  <div class="row">
    <div class="toukou">
    <div class="col-sm-8">
      <%= form_with(model: @post, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <%= f.select :genre, ['食事', '運動', '美容'], {include_blank: 'ジャンル選択'}, class: 'form-control' %>
        <div class="form-group">
          <p class="gazou">
            <%= f.label :image, '画像をアップロード' %>
            <br>
            <%= f.file_field :image %>
          </p>
          <%= f.text_area :content, class: 'form-control', rows: 5 %>
        </div>
        <%= f.submit '投稿する', class: 'btn btn-primary btn-block' %>
      <% end %>
    </div>
    </div>
  </div>
<% end %>

app/views/posts/search.html.erb
<p>検索</p>
<%= form_tag(search_path,:method => 'get') do %>
  <%= text_field_tag :search %>
  <%= submit_tag 'Search', :name => nil %>
<% end %>

<ul><% @posts.each do |post| %>
  <li>
    <%= link_to post.title, post %>
    <%= post.created_at %>
    <%= post.status %>
  </li>
  <%= link_to "編集",edit_post_path(post) %>
  <%= link_to "削除",post, method: :delete %>
  <% end %>
</ul>

app/views/posts/show.html.erb
<div class="row">
  <div class="toukou">
    <div class="col-sm-8">
        <h1 class="edit_top" >編集結果</h1>
        <div class="edit_change" >
<%= link_to 'Myタイムライン へ', root_path %>
<br>
<%= link_to 'Myプロフィール へ', user_path(@current_user) %>
<br>
<%= link_to 'このメモを編集する', edit_post_path(@post) %>
<br>
<%= link_to 'このメモを削除する', @post, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %>
</div>
<br>
<div class="edit_genre" >
<p>
  <label>ジャンル</label> <%= @post.genre %>
</p>
</div>
<div class="form-group">
      <p class="gazou">
<%= image_tag @post.image.url, alt: "KIREI_image" %>
</p>
<div class="edit_memo" >
    <p>
        <label>メモ</label>
        <br>
        <%= @post.content %>
        </p>
    </div>
</div>

</div>
  </div>
</div>